services:

    validator.countryandcity:
        class: YOC\Validator\CountryAndCityValidator
        calls:
            - method: setContainer
              arguments:
                  - '@service_container'